[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "click>=8.2.1",
    "pillow>=11.2.1",
    "prompt-toolkit>=3.0.51",
    "requests>=2.32.4",
    "rich>=14.0.0",
]
